---
title: "Data checks"
author: "Ana Martinovici"
date: "Last compiled on `r Sys.Date()`"
output: 
    html_document:
        toc: true
        toc_float: 
            collapsed: false
        number_sections: true
        code_folding: hide
        theme: cerulean
editor_options: 
  chunk_output_type: console
---

```{r}
library("qualtRics")
library("tidyverse")

```


```{r}

data_1 <- qualtRics::read_survey(here::here("data_export",
							  "qualtrics_checks_August+3,+2023_10.57.csv"))

data_2 <- qualtRics::read_survey(here::here("data_export",
							  "qualtrics_checks_August+3,+2023_11.08.csv"))


```

`data_1` is the original dataset. `data_2` has 3 modified responses.

```{r}
anti_join(data_1,
	    data_2,
	    by = colnames(data_1))

anti_join(data_2,
	    data_1,
	    by = colnames(data_1))


```


```{r}
data_3 <- qualtRics::read_survey(here::here("data_export",
							  "qualtrics_checks_August+3,+2023_11.17.csv"))

anti_join(data_1,
	    data_3,
	    by = colnames(data_1))
anti_join(data_1,
	    data_3,
	    by = colnames(data_1)) %>%
	select(A_text,
		 B_text,
		 ALL_text)
inner_join(data_1,
	     data_3,
	     by = colnames(data_1)) %>%
	select(A_text,
		 B_text,
		 ALL_text)
```

Compare data exported with "exclude survey response edits" (data_3) and without (data_2)

```{r}
anti_join(data_2,
	    data_3,
	    by = colnames(data_2))

anti_join(data_3,
	    data_2,
	    by = colnames(data_2)) %>%
	select(A_text,
		 B_text,
		 ALL_text)

```



